FROM golang:1.22.5 AS build

WORKDIR /app

COPY . /app
RUN cd /app/src/ && make build

FROM alpine:edge

WORKDIR /app
COPY --from=build /app/src/build/ocf-amd64 .
RUN apk --no-cache add ca-certificates tzdata

ENTRYPOINT ["/app/ocf-amd64"]