networks:
  ocf-internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.200.0/24

services:
  global-dispatcher:
    image: ocf-amd64
    build:
      context: ../
      dockerfile: ./local-demo/docker/dispatcher/Dockerfile
    command:
      [
        "start",
        "--mode",
        "standalone",
        "--seed",
        "0",
        "--public-addr",
        "192.168.200.10"
      ]
    volumes:
      - ./env/id.dispatcher:/root/.ocfcore/keys/id
    networks:
      ocf-internal:
        ipv4_address: 192.168.200.10
    ports:
      - 8092:8092
      - 43905:43905
  llm-srevice:
    image: ocf-sql-amd64
    build:
      context: ../
      dockerfile: ./local-demo/docker/llm-serving/Dockerfile
    command:
      [
        "start",
        "--seed",
        "0",
        "--bootstrap.addr",
        "/ip4/192.168.200.10/tcp/43905/p2p/QmcMpnf39qfJcXssHrFFw7nvAioLd4SXKhzBZ4XMcLDoSU",
        "--subprocess",
        "uvicorn serving-engine.main:app --host 0.0.0.0 --port 8080",
        "--service.name",
        "llm",
        "--service.port",
        "8080"
      ]
    volumes:
      - ./env/id.llm:/root/.ocfcore/keys/id
    networks:
      ocf-internal:
        ipv4_address: 192.168.200.21
    ports:
      - 8093:8092
      - 43906:43905
