networks:
  ocf-internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.200.0/24

services:
  global-dispatcher:
    image: ocf-amd64
    build:
      context: ../
      dockerfile: ./local-demo/docker/dispatcher/Dockerfile
    command:
      [
        "start",
        "--mode",
        "standalone",
        "--seed",
        "0",
        "--public-addr",
        "192.168.200.10"
      ]
    volumes:
      - ./env/id.dispatcher:/root/.ocfcore/keys/id
    networks:
      ocf-internal:
        ipv4_address: 192.168.200.10
    ports:
      - 8092:8092
      - 43905:43905
  llm-srevice-1:
    image: ocf-sql-amd64
    build:
      context: ../
      dockerfile: ./local-demo/docker/llm-serving/Dockerfile
    command:
      [
        "start",
        "--seed",
        "0",
        "--bootstrap.addr",
        "/ip4/192.168.200.10/tcp/43905/p2p/QmcMpnf39qfJcXssHrFFw7nvAioLd4SXKhzBZ4XMcLDoSU",
        "--subprocess",
        "uvicorn serving-engine.main:app --host 0.0.0.0 --port 8080",
        "--service.name",
        "llm",
        "--service.port",
        "8080"
      ]
    volumes:
      - ./env/id.llm:/root/.ocfcore/keys/id
    networks:
      ocf-internal:
        ipv4_address: 192.168.200.21
    ports:
      - 8093:8092
      - 43906:43905
  llm-srevice-2:
    image: ocf-sql-amd64
    build:
      context: ../
      dockerfile: ./local-demo/docker/llm-serving/Dockerfile
    command:
      [
        "start",
        "--bootstrap.addr",
        "/ip4/192.168.200.10/tcp/43905/p2p/QmcMpnf39qfJcXssHrFFw7nvAioLd4SXKhzBZ4XMcLDoSU",
        "--subprocess",
        "uvicorn serving-engine.main:app --host 0.0.0.0 --port 8080",
        "--service.name",
        "llm",
        "--service.port",
        "8080"
      ]
    networks:
      ocf-internal:
        ipv4_address: 192.168.200.22
    ports:
      - 8094:8092
      - 43907:43905

  llm-srevice-3:
    image: ocf-sql-amd64
    build:
      context: ../
      dockerfile: ./local-demo/docker/llm-serving/Dockerfile
    command:
      [
        "start",
        "--bootstrap.addr",
        "/ip4/192.168.200.10/tcp/43905/p2p/QmcMpnf39qfJcXssHrFFw7nvAioLd4SXKhzBZ4XMcLDoSU",
        "--subprocess",
        "uvicorn serving-engine.main:app --host 0.0.0.0 --port 8080",
        "--service.name",
        "llm",
        "--service.port",
        "8080"
      ]
    networks:
      ocf-internal:
        ipv4_address: 192.168.200.23
    ports:
      - 8095:8092
      - 43908:43905

  llm-srevice-4:
    image: ocf-sql-amd64
    build:
      context: ../
      dockerfile: ./local-demo/docker/llm-serving/Dockerfile
    command:
      [
        "start",
        "--bootstrap.addr",
        "/ip4/192.168.200.10/tcp/43905/p2p/QmcMpnf39qfJcXssHrFFw7nvAioLd4SXKhzBZ4XMcLDoSU",
        "--subprocess",
        "uvicorn serving-engine.main:app --host 0.0.0.0 --port 8080",
        "--service.name",
        "llm",
        "--service.port",
        "8080"
      ]
    networks:
      ocf-internal:
        ipv4_address: 192.168.200.24
    ports:
      - 8096:8092
      - 43910:43905

  llm-srevice-5:
    image: ocf-sql-amd64
    build:
      context: ../
      dockerfile: ./local-demo/docker/llm-serving/Dockerfile
    command:
      [
        "start",
        "--bootstrap.addr",
        "/ip4/192.168.200.10/tcp/43905/p2p/QmcMpnf39qfJcXssHrFFw7nvAioLd4SXKhzBZ4XMcLDoSU",
        "--subprocess",
        "uvicorn serving-engine.main:app --host 0.0.0.0 --port 8080",
        "--service.name",
        "llm",
        "--service.port",
        "8080"
      ]
    networks:
      ocf-internal:
        ipv4_address: 192.168.200.25
    ports:
      - 8097:8092
      - 43911:43905

  llm-srevice-6:
    image: ocf-sql-amd64
    build:
      context: ../
      dockerfile: ./local-demo/docker/llm-serving/Dockerfile
    command:
      [
        "start",
        "--bootstrap.addr",
        "/ip4/192.168.200.10/tcp/43905/p2p/QmcMpnf39qfJcXssHrFFw7nvAioLd4SXKhzBZ4XMcLDoSU",
        "--subprocess",
        "uvicorn serving-engine.main:app --host 0.0.0.0 --port 8080",
        "--service.name",
        "llm",
        "--service.port",
        "8080"
      ]
    networks:
      ocf-internal:
        ipv4_address: 192.168.200.26
    ports:
      - 8098:8092
      - 43912:43905
  
  llm-srevice-7:
    image: ocf-sql-amd64
    build:
      context: ../
      dockerfile: ./local-demo/docker/llm-serving/Dockerfile
    command:
      [
        "start",
        "--bootstrap.addr",
        "/ip4/192.168.200.10/tcp/43905/p2p/QmcMpnf39qfJcXssHrFFw7nvAioLd4SXKhzBZ4XMcLDoSU",
        "--subprocess",
        "uvicorn serving-engine.main:app --host 0.0.0.0 --port 8080",
        "--service.name",
        "llm",
        "--service.port",
        "8080"
      ]
    networks:
      ocf-internal:
        ipv4_address: 192.168.200.27
    ports:
      - 8099:8092
      - 43913:43905
  
  llm-srevice-8:
    image: ocf-sql-amd64
    build:
      context: ../
      dockerfile: ./local-demo/docker/llm-serving/Dockerfile
    command:
      [
        "start",
        "--bootstrap.addr",
        "/ip4/192.168.200.10/tcp/43905/p2p/QmcMpnf39qfJcXssHrFFw7nvAioLd4SXKhzBZ4XMcLDoSU",
        "--subprocess",
        "uvicorn serving-engine.main:app --host 0.0.0.0 --port 8080",
        "--service.name",
        "llm",
        "--service.port",
        "8080"
      ]
    networks:
      ocf-internal:
        ipv4_address: 192.168.200.28
    ports:
      - 8100:8092
      - 43914:43905

  llm-srevice-9:
    image: ocf-sql-amd64
    build:
      context: ../
      dockerfile: ./local-demo/docker/llm-serving/Dockerfile
    command:
      [
        "start",
        "--bootstrap.addr",
        "/ip4/192.168.200.10/tcp/43905/p2p/QmcMpnf39qfJcXssHrFFw7nvAioLd4SXKhzBZ4XMcLDoSU",
        "--subprocess",
        "uvicorn serving-engine.main:app --host 0.0.0.0 --port 8080",
        "--service.name",
        "llm",
        "--service.port",
        "8080"
      ]
    networks:
      ocf-internal:
        ipv4_address: 192.168.200.29
    ports:
      - 8101:8092
      - 43915:43905

  llm-srevice-0:
    image: ocf-sql-amd64
    build:
      context: ../
      dockerfile: ./local-demo/docker/llm-serving/Dockerfile
    command:
      [
        "start",
        "--bootstrap.addr",
        "/ip4/192.168.200.10/tcp/43905/p2p/QmcMpnf39qfJcXssHrFFw7nvAioLd4SXKhzBZ4XMcLDoSU",
        "--subprocess",
        "uvicorn serving-engine.main:app --host 0.0.0.0 --port 8080",
        "--service.name",
        "llm",
        "--service.port",
        "8080"
      ]
    networks:
      ocf-internal:
        ipv4_address: 192.168.200.30
    ports:
      - 8102:8092
      - 43916:43905
